default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: Rails_kadai2_development
test:
  <<: *default
  database: Rails_kadai2_test
production:
  <<: *default
  database: Rails_kadai2_production
  username: Rails_kadai2
  password: <%= ENV['RAILS_KADAI2_DATABASE_PASSWORD'] %>
